
export const Skill = [
    'JavaScript',
    'React.js',
    'Node.js',
    'AngularJS',
    'Vue.js',
    'Java',
    'Spring Framework',
    'Hibernate',
    'Apache Struts',
    'JavaFX',
    'Python',
    'Django',
    'Flask',
    'NumPy',
    'Pandas',
    'C#',
    'ASP.NET',
    '.NET Core',
    'Unity',
    'Xamarin',
    'Ruby',
    'Ruby on Rails',
    'Sinatra',
    'RSpec',
    'Capybara',
    'PHP',
    'Laravel',
    'Symfony',
    'CodeIgniter',
    'WordPress',
    'Swift',
    'iOS app development',
    'macOS app development',
    'SwiftUI',
    'Kotlin',
    'Android app development',
    'Kotlin Multiplatform',
    'TypeScript',
    'Angular',
    'Vue.js',
    'React Native',
    'Deno',
    'Go',
    'Google Cloud Platform',
    'Docker',
    'Kubernetes',
    'Rust',
    'Systems programming',
    'Web development',
    'Networking',
    'C/C++',
    'Embedded systems',
    'Game development',
    'Operating systems',
    'SQL',
    'Database management',
    'Querying and manipulating data',
    'HTML/CSS',
    'Web development',
    'Front-end design',
    'MATLAB',
    'Numerical computing',
    'Data analysis',
    'R',
    'Statistical computing',
    'Data visualization',
    'Machine learning'
  ];
  export const Educations = [
    'BCA',
    'MCA',
    'BBA',
    'MBA',
    'B.Tech',
    'M.Tech',
    'B.Sc.',
    'M.Sc',
    'BE',
    'ME',
    'Any Computer Streams',
    'Any UG',
    'Any PG',
    'Others'
  ];
  
  export const Locations = ['Coimbatore', 'Chennai', 'Bengaluru'];
  